services:
  finance_bot:
    build: .
    container_name: my-finance-bot
    restart: always
    # Подгружаем переменные из .env
    env_file:
      - .env
    # Пробрасываем базу данных наружу, чтобы она не стерлась
    volumes:
      - ./transactions.json:/app/transactions.json
    # Настройка логирования, чтобы логи не съели всё место на диске
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"